version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: textdiff-backend
    restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME:-TextDiff}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - DEBUG=${DEBUG:-False}
      - DATABASE_URL=${DATABASE_URL:-mysql+pymysql://work:s4TUPM.qXmfvAUu@23.19.231.78:3306/textdiff?charset=utf8mb4}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this-in-production}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
      - ALLOWED_ORIGINS=["http://localhost", "http://localhost:80"]
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    ports:
      - "8000:8000"
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: textdiff-frontend
    restart: unless-stopped
    network_mode: "bridge"

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: textdiff-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    network_mode: "bridge"
    links:
      - backend
      - frontend

volumes:
  backend_data:
    driver: local
  nginx_logs:
    driver: local
